apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: waitforfirstconsumer-storage
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: waitforfirstconsumer-storage
  hostPath:
    path: /home/docker/workspace

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: waitforfirstconsumer-storage