apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-volume
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /home/docker/workspace


---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage