name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/kubernetes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      uses: medyagh/setup-minikube@master

    - name: Start Minikube
      run: minikube start --driver=docker

    - name: Create Kaniko secret
      run: |
        kubectl create secret docker-registry regcred \
          --docker-server=https://index.docker.io/v1/ \
          --docker-username=${{ secrets.DOCKER_USERNAME }} \
          --docker-password=${{ secrets.DOCKER_PASSWORD }} \
          --docker-email=${{ secrets.DOCKER_EMAIL }}

    - name: Create workspace directory in Minikube
      run: |
        minikube ssh -- sudo mkdir -p workspace

    - name: Copy code to Minikube workspace
      run: |
        minikube cp Dockerfile minikube:/home/docker/workspace/ 
        minikube cp tsconfig.json minikube:/home/docker/workspace/
        minikube cp tsconfig.build.json minikube:/home/docker/workspace/

    - name: Create Kaniko Job to build the image and to push the image to dockerhub
      run: |
        kubectl apply -f volume.yaml
        kubectl apply -f job.yaml

    - name: Get Kaniko Job Events (if job fails)
      run: |
        kubectl events

    - name: Get Kaniko Job Events (if job fails)
      run: |
        kubectl events

    - name: Wait for Kaniko Job to finish
      run: |
        kubectl wait --for=condition=complete job/kaniko-job --timeout=5m

    - name: Get Kaniko Job Events (if job fails)
      run: |
        kubectl events

    - name: Get Kaniko Job Events for kaniko-job (if job fails)
      if: failure()
      run: |
        kubectl get events --field-selector involvedObject.name=kaniko-job

    - name: Describe Kaniko Job (if job fails)
      if: failure()
      run: |
        kubectl describe job kaniko-job

    - name: Clean up Kaniko Job
      run: |
        kubectl delete job kaniko-job
