name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/kubernetes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      uses: medyagh/setup-minikube@master

    - name: Start Minikube
      run: minikube start --driver=docker

    - name: Check storageclass
      run: kubectl get storageclass

    - name: Describe sc
      run: kubectl describe sc

    - name: Create Kaniko secret
      run: |
        kubectl create secret docker-registry regcred \
          --docker-server=https://index.docker.io/v1/ \
          --docker-username=${{ secrets.DOCKER_USERNAME }} \
          --docker-password=${{ secrets.DOCKER_PASSWORD }} \
          --docker-email=${{ secrets.DOCKER_EMAIL }}

    - name: Create workspace directory in Minikube
      run: |
        minikube ssh -- sudo mkdir -p workspace

    - name: Copy code to Minikube workspace
      run: |
        minikube cp Dockerfile minikube:/home/docker/workspace/ 
        minikube cp tsconfig.json minikube:/home/docker/workspace/
        minikube cp tsconfig.build.json minikube:/home/docker/workspace/

    - name: Create Kaniko Job to build the image and to push the image to dockerhub
      run: |
        kubectl create -f volume.yaml --v=6
        kubectl create -f pod-test.yaml --v=6

    - name: Describe Workspace claim 
      run: |
        kubectl describe pvc workspace-claim --v=6

    - name: Get Kaniko Job Events
      run: |
        kubectl events

    - name: Get Kaniko Pod Logs
      run: |
        kubectl logs kaniko

    - name: get pods
      run: |
        kubectl get pods

    - name: Get Kaniko Pod Logs
      run: |
        kubectl logs kaniko

    - name: GET KANIKO LOGS
      run: |
        kubectl logs kaniko

    - name: WAIT WHEN READY
      run: |
        kubectl wait --for=condition=Ready pod/kaniko

    - name: WAIT WHEN READY=FALSE
      run: |
        kubectl wait --for=condition=Ready-false pod/kaniko

    - name: Watch kaniko job events real time
      run: |
        kubectl get events -w --v=6

    - name: GET KANIKO LOGS
      run: |
        kubectl logs kaniko

    - name: Describe Kaniko pod (if job fails)
      if: failure()
      run: |
        kubectl describe pod kaniko

    - name: Clean up Kaniko pod
      run: |
        kubectl delete pod kaniko
